### ISSUE TITLE
what is the license on this repo?

### ISSUE THREAD

**Issue by job** [packetsource/rfc8212-junos#3]
What license?

**Comment by packetsource** [comment]
Oh I'm not a pro on all these public licenses for rescinding default
copyright. I figure I've sold the farm by putting it on github anyway.

Is there something specific you need, Job - like something written to use
it in production, or to use it in a paper? Assume any terms acceptable that
include discretionary citation/attribution of original work and
indemnification of liability for consequential loss/damages.

MIT terms from my brief bath-time googling...?

One thing, though. If you're going to punt this into production somewhere,
let me kill some exhaustive testing on it this week.

**Comment by job** [comment]
All published software should have a license, this makes it easier for
people to figure out what they can and can’t do. :-)

I’m personally a fan of MIT or BSD style licenses, but this is your work so
you have to pick something! :-)

**Comment by packetsource** [comment]
Thanks Job. MIT it is.
